# Generated by Django 3.2 on 2021-04-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=20)),
                ('branch', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('customer_type', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('product_line', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.FloatField(blank=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('tax', models.FloatField(blank=True)),
                ('total', models.FloatField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('cogs', models.FloatField(blank=True)),
                ('gross_income', models.FloatField(blank=True)),
                ('rating', models.FloatField(blank=True)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
